api_platform:
    title: API portfolio Romain Chardon
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']

    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
